# Generated by Django 6.0.5 on 2026-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donationrecord_customuser_last_seen_communitymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='youtube_url',
            field=models.TextField(help_text="Collez l'URL YouTube (watch, youtu.be, embed) ou directement le code <iframe> fourni par YouTube.", verbose_name='URL ou code embed YouTube'),
        ),
    ]
