# Generated by Django 6.0.5 on 2026-05-25 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_phone_approved_google_phoneverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingproject',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Objectif (FCFA)'),
        ),
        migrations.AlterField(
            model_name='fundingproject',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Collecté (FCFA)'),
        ),
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug URL')),
                ('category', models.CharField(choices=[('inspiration', 'Inspiration'), ('actualites', 'Actualités'), ('temoignages', 'Témoignages'), ('mission', 'Mission & Actions'), ('education', 'Éducation'), ('sante', 'Santé')], max_length=30, verbose_name='Catégorie')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Résumé')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
