# Generated by Django 6.0.5 on 2026-05-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'émission")),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('category', models.CharField(choices=[('culte', 'Culte & Prière'), ('temoignage', 'Témoignages'), ('enfants', 'Programme Enfants'), ('enseignement', 'Enseignement Biblique'), ('actualites', 'Actualités & Infos'), ('musique', 'Louange & Musique'), ('special', 'Émission Spéciale'), ('conference', 'Conférence')], default='culte', max_length=30, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('presenter', models.CharField(blank=True, max_length=100, verbose_name='Présentateur·rice')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='emissions/', verbose_name='Miniature')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Mise en avant')),
            ],
            options={
                'verbose_name': 'Créneau émission',
                'verbose_name_plural': 'Grille des émissions',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False, verbose_name='En direct maintenant')),
                ('title', models.CharField(default="Children's Fruit Live", max_length=200, verbose_name='Titre du direct')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube Live'), ('facebook', 'Facebook Live'), ('hls', 'Flux HLS (nginx-rtmp / SRS / mediamtx)')], default='youtube', max_length=20, verbose_name='Plateforme')),
                ('stream_url', models.TextField(blank=True, help_text='URL YouTube Live (watch/embed), URL HLS .m3u8, ou URL Facebook Live', verbose_name='URL du flux')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré à')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='livestream/', verbose_name='Image hors-direct')),
            ],
            options={
                'verbose_name': 'Diffusion Live',
                'verbose_name_plural': 'Diffusions Live',
                'ordering': ['-started_at'],
            },
        ),
    ]
