# Generated by Django 6.0.5 on 2026-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_livestream_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Formats acceptés : MP4, WebM, OGG. Laissez vide si vous utilisez une URL YouTube.', null=True, upload_to='videos/', verbose_name='Fichier vidéo'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='youtube_url',
            field=models.TextField(blank=True, help_text="Collez l'URL YouTube (watch, youtu.be, embed) ou directement le code <iframe> fourni par YouTube.", verbose_name='URL ou code embed YouTube'),
        ),
    ]
