# Generated by Django 6.0.5 on 2026-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_videocontent_file_youtube_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/'),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('sticker', 'Sticker'), ('voice', 'Vocal')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='sticker_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='chat/voice/'),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='text',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
