# Generated by Django 6.0.5 on 2026-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_communitymessage_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chat/documents/'),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='chat/videos/'),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('sticker', 'Sticker'), ('voice', 'Vocal'), ('video', 'Vidéo'), ('document', 'Document')], default='text', max_length=10),
        ),
    ]
