# Generated by Django 6.0.5 on 2026-05-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_communitymessage_video_document_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestream',
            options={'ordering': ['-started_at'], 'permissions': [('can_manage_live', 'Peut gérer le live (contrôle & planning)')], 'verbose_name': 'Diffusion Live', 'verbose_name_plural': 'Diffusions Live'},
        ),
    ]
