# Generated by Django 6.0.5 on 2026-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_courseresource_studycourse_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'Document PDF'), ('word', 'Document Word'), ('video', 'Vidéo'), ('audio', 'Audio / Podcast')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approuvé par admin'),
        ),
    ]
